export enum LineOfWork {
  architectureEngineering = 'Architecture and Engineering Occupations',
  artMedia = 'Arts, Design, Entertainment, Sports, and Media Occupations',
  buildingMaintenance = 'Building and Grounds Cleaning and Maintenance Occupations',
  businessFinancial = 'Business and Financial Operations Occupations',
  socialServices = 'Community and Social Services Occupations',
  computerMath = 'Computer and Mathematical Occupations',
  construction = 'Construction and Extraction Occupations',
  education = 'Education, Training, and Library Occupations',
  farming = 'Farming, Fishing, and Forestry Occupations',
  restoration = 'Food Preparation and Serving Related Occupations',
  healthcare = 'Healthcare Practitioners and Technical Occupations',
  supportHealthcare = 'Healthcare Support Occupations',
  repairMaintenance = 'Installation, Maintenance, and Repair Occupations',
  legal = 'Legal Occupations',
  physical = 'Life, Physical, and Social Science Occupations',
  management = 'Management Occupations',
  military = 'Military Specific Occupations',
  administrative = 'Office and Administrative Support Occupations',
  care = 'Personal Care and Service Occupations',
  production = 'Production Occupations',
  protective = 'Protective Service Occupations',
  sales = 'Sales and Related Occupations',
}
