export const SIMULATION: { [id: string]: string } = {
  nSocial: 'Social Number',
  fSocial: 'social',
  fSocialErr: 'socialDigits',
  nTime: 'Time  Working as Independent',
  fTime: 'itime',
  fTimeErr: 'iTimeGreater',
  nAverage: 'Average Monthly Income',
  fAverage: 'iaverage',
  fAverageErr: 'iAverageGreater',
  nAnnual: 'Annual Income',
  fAnual: 'iannual',
  fAnnualErr: 'iAnnualGreater',
  nLineWork: 'Line of Work',
  fLineWork: 'linework',
  nType: 'Worker Type',
  fType: 'type',
  nProduct: 'Product to Simulate',
  fProduct: 'product',
  nAmount: 'Amount',
  fAmount: 'amount',
  nFinanced: 'Financed Amount',
  fFinanced: 'financed',
  fFinancedErr: 'financedHigher',
  nMonths: 'Months Needed',
  fMonths: 'months',
  fMonthsErr: 'monthsNotValue',
  nPersonal: 'Personal Networth',
  fPersonal: 'personal',
  fPersonalErr: 'iPersonalGreater',
  nChronic: 'Chronic Diseases',
  fChronic: 'chronic',
  nCompany: 'Company',
  fCompany: 'company',
  nCSocial: 'Company Social Number',
  fCSocial: 'csocial',
  nTimeWork: 'Time Working in the Company',
  fTimeWork: 'timework',
  fTimeWorkErr: 'iTimeworkGreater',
  nNet: 'Net Salary',
  fNet: 'net',
  fNetErr: 'iNetGreater',
  nCLineWork: 'Company Line of Work',
  fCLineWork: 'clinework',
  nAge: 'Age',
  fAge: 'age',
  fAgeErr: 'age',
  fAgeTErr: 'ageTime',
  nGuarantor: 'Needs Guarantor',
  fGuarantor: 'bguarantor',
  fGuarantors: 'guarantors',
};
